version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: doitup02
      DB_NAME: postgres

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: doitup02
      DB_NAME: postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
    depends_on:
      - user-service
      - product-service

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doitup02
    ports:
      - "5432:5432"
